### ISSUE TITLE
Accessing show img on the show itself  

### ISSUE THREAD

**Issue by mazenemam19** [EdgarVaguencia/tvtime-api#3]
Hi there, thanks for the great tool, I'm really enjoying it!

I'm trying to build a favorite section similar to the one you have on your profile page in tvtime, as it is, there's no way of accessing  show images unless you loop over all your shows (unless I'm mistaken) which doesn't serve the case, as I'm adding shows using the show Id, is there a way of accessing the image on a specific show?

**Comment by EdgarVaguencia** [comment]
I didn't think it was relevant to include the image, but I think it's easy to include.

**Comment by mazenemam19** [comment]
I hacked my way around it for now by slicing the array returned from `tvtime.shows()`, but yeah It might be useful in case you only want to add a specific show by the id

**Comment by Versifiction** [comment]
@EdgarVaguencia sorry to write it here, but I've been trying to reach you about 1 question : I use TV Time with my linked Twitter account, what do I put in the username and password login method please ?

**Comment by EdgarVaguencia** [comment]
@Versifiction sorry but only work with "origin login" (tvtime user)
