### ISSUE TITLE
Accessing all shows full information

### ISSUE THREAD

**Issue by mazenemam19** [EdgarVaguencia/tvtime-api#4]
Hi again,

I'm also trying to build the All shows section on the profile page with the show watching progress bar,
this is how I approached it
```
try{
	  const fetchSeries = async () => {
	  const user = await tvtime.login(username, password)
	  const shows = await tvtime.shows()
	  const showsId = [];
	  shows.map(show=>showsId.push(show.id))
	  const showsArray=[]
	  for (var id of showsId) {
	      const show = await tvtime.show(id)
		showsArray.push(show)
           }
	}
	fetchSeries()
} catch(e) {
	console.log(e)
}
```
this method should work (I think ... couldn't finish test it as I've too many shows being fetched😅), but `tvtime.show(id)` takes a relatively long time fetching show data depending on how long the show is, any idea how can I make this process faster?

**Comment by EdgarVaguencia** [comment]
Look the fork @atagulalan, he fetch all shows from a global variable and it might work for your purpos

**Comment by atagulalan** [comment]
This might come in handy: https://github.com/atagulalan/tvtime-backup

**Comment by mazenemam19** [comment]
will check it out, thanks a lot :smile:
